---
# This is the default configuration file which will be merged with file passed
# by:
#
# * --ocp4mcoci-conf file.yaml parameter.
#
# Each section in this file will be available as an attribute of the
# framework.conf object.
#
# ------------------------------------------------------------------------

# in this RUN section we will keep default parameters for run of ocp4-mco-ci
RUN:
  bin_dir: './bin'
  log_level: "INFO"
  kubeconfig_location: 'auth/kubeconfig' # relative from cluster_dir
  username: 'kubeadmin' # default user
  password_location: 'auth/kubeadmin-password' # relative from cluster_dir
  # If the client version ends with .nightly, the version will be exposed
  # to the latest accepted OCP nightly build version
  client_version: '4.12.0-0.nightly'
  # Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  https_certification_verification: true

# In this section we are storing all deployment related configuration but not
# the environment related data as those are defined in ENV_DATA section.
DEPLOYMENT:
  # if the installer version ends with .nightly, the version will be exposed
  # to the latest accepted OCP nightly build version. You can also use the
  # specific build version like: "4.2.0-0.nightly-2019-08-06-195545"
  installer_version: "4.11.2"
  force_download_installer: true
  force_download_client: true
  skip_download_client: false
  ssh_key: "~/.ssh/openshift-dev.pub"
  ssh_key_private: "~/.ssh/openshift-dev.pem"
  ocp_mirror_url: "https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com"

# This is the default information about environment.
ENV_DATA:
  # OCP
  cluster_name: 'odf-cluster'
  cluster_path: "/tmp/odf-cluster"
  platform: 'AWS'
  region: 'us-east-2'
  master_instance_type: 'm4.2xlarge'
  worker_instance_type: 'm5.4xlarge'
  master_replicas: 3
  worker_replicas: 3
  skip_ocp_deployment: false
  base_domain: 'makestoragegreatagain.com'
  # The subnet prefix length to assign to each individual node.
  # For example, if hostPrefix is set to 23, then each node is assigned a /23 subnet out of the given cidr,
  # which allows for 510 (2^(32 - 23) - 2) pod IPs addresses.
  # https://docs.openshift.com/container-platform/4.1/installing/installing_bare_metal/installing-bare-metal.html
  cluster_host_prefix: 23
  cluster_network_cidr: '10.128.0.0/14'
  service_network_cidr: '172.30.0.0/16'

  # OCS
  ocs_version: '4.12'
  skip_ocs_deployment: true
  skip_ocs_cluster_creation: true
  # enable console plugin
  enable_ocs_plugin: false
  # you can overwrite the image for ocs operator catalog source by following parameter:
  # ocs_registry_image: "quay.io/rhceph-dev/ocs-olm-operator:4.2-32.9b6c93e.master"
  default_ocs_registry_image: "quay.io/rhceph-dev/ocs-registry:latest"
  # You can overwrite csv channel version by following parameter
  # This is same of all ODF operators
  ocs_csv_channel: "stable-4.12"

# All Multicluster stuff here
MULTICLUSTER:
  # Index of this cluster Config in a list of cluster Configs
  multicluster_index: 0
  # Indicating the current cluster is acm cluster
  acm_cluster: false
  # Indicating the current cluster is a DR primary cluster
  # acm cluster also can be DR primary cluster
  primary_cluster: false

  # MCO
  # To control MCO installation
  skip_mco_deployment: true
  # enable console plugin
  enable_mco_plugin: false

  # ACM HUB deployment
  # To control acm installation
  deploy_acm_hub_cluster: false
  acm_hub_unreleased: false
  # only for released acm version
  acm_hub_channel: 'release-2.5'
  # override this using: acm_unreleased_image
  default_acm_unreleased_image: "2.5.2-DOWNSTREAM-2022-07-29-15-56-49"

  # Submariner
  # To control submainer configuration
  configure_submariner: false
  submariner_source: "upstream"
  submariner_url: "https://get.submariner.io"
  submariner_info_file: "broker-info.subm"

  # ACM managed cluster import
  import_managed_clusters: false

  # SSL access across clusters
  # For more info: https://docs.google.com/document/d/1MfSmXbiGI76As3_nNElsdmibpSIduxi8jquwO1HGuYY/edit#heading=h.bh2etop7o3f
  exchange_ssl_certificate: false

  # GitOps
  # To control GitOps installation
  skip_gitops_deployment: true

# Section for reporting configuration
REPORTING:
  email:
    skip_notification: true
    smtp_server: "localhost"
    recipients: '' # comma separated email ids without space
