RUN:
  client_version: 'latest-4.14'
DEPLOYMENT:
  force_download_installer: true
  installer_version : "latest-4.14"
  ssh_key: "~/.ssh/id_rsa.pub"
  ocp_mirror_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview"
ENV_DATA:
  base_domain: makestoragegreatagain.com
  region: 'us-east-2'
  skip_ocp_deployment: false
  skip_ocs_deployment: false
  skip_ocs_cluster_creation: true
  enable_ocs_plugin: true
  ocs_registry_image: "quay.io/rhceph-dev/ocs-registry:latest-stable-4.14.0"
  ocs_csv_channel: "stable-4.14"
  ocs_version: '4.14'
REPORTING:
  email:
    skip_notification: false
