RUN:
  client_version: 'candidate-4.14'
DEPLOYMENT:
  force_download_installer: true
  installer_version : 'candidate-4.14'
  ssh_key: '~/.ssh/id_rsa.pub'
  ocp_mirror_url: 'https://mirror.openshift.com/pub/openshift-v4/clients/ocp/'
ENV_DATA:
  base_domain: 'makestoragegreatagain.com'
  region: 'us-west-2'
  service_network_cidr: '172.31.0.0/16'
  cluster_network_cidr: '10.132.0.0/14'
  master_instance_type: 'm5.xlarge'
  worker_instance_type: 'm5.2xlarge'
  skip_ocp_deployment: false
  skip_ocs_deployment: false
  skip_ocs_cluster_creation: false
  enable_ocs_plugin: true
  ocs_registry_image: 'quay.io/rhceph-dev/ocs-registry:latest-stable-4.14.0'
  ocs_csv_channel: 'stable-4.14'
  ocs_version: '4.14'
REPORTING:
  email:
    skip_notification: true
