RUN:
  client_version: 'candidate-4.14'
DEPLOYMENT:
  force_download_installer: true
  installer_version : 'candidate-4.14'
  ssh_key: '~/.ssh/id_rsa.pub'
  ocp_mirror_url: 'https://mirror.openshift.com/pub/openshift-v4/clients/ocp/'
ENV_DATA:
  base_domain: 'makestoragegreatagain.com'
  region: 'us-east-2'
  master_instance_type: 'm5.2xlarge'
#  worker_instance_type: 'm5.2xlarge'
  master_replicas: 3
  worker_replicas: 0
  skip_ocp_deployment: false
  skip_ocs_deployment: true
  skip_ocs_cluster_creation: true
  enable_ocs_plugin: false
  ocs_registry_image: 'quay.io/rhceph-dev/ocs-registry:latest-stable-4.14.0'
  ocs_csv_channel: 'stable-4.14'
  ocs_version: '4.14'
MULTICLUSTER:
  acm_cluster: true
  primary_cluster: false
  configure_submariner: false
  skip_mco_deployment: true
  enable_mco_plugin: false
  deploy_acm_hub_cluster: true
  import_managed_clusters: true
  exchange_ssl_certificate: true
  skip_gitops_deployment: false
  # comment this out for acm unreleased version
  # acm_hub_channel: 'release-2.7'
  # enable this for ACM un-released build
  acm_hub_unreleased: true
  acm_unreleased_image: '2.9.0-DOWNSTREAM-2023-09-27-22-12-46'
REPORTING:
  email:
    skip_notification: true
